[package]
name = "geoip"
version = "0.1.0"
authors = ["Aleksandr Pak <alekspak@icloud.com>"]

[dependencies.micro]
path = "../../../../micro"

[dependencies]
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"
